'use client'

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import DoctorFooter from "@/components/DoctorFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    if (isOpen) {
      const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth;
      document.documentElement.style.overflow = "hidden"; // Prevent scroll
      document.documentElement.style.paddingRight = `${scrollbarWidth}px`;
      document.body.style.overflow = "hidden";
      document.body.style.paddingRight = `${scrollbarWidth}px`;
    } else {
      document.documentElement.style.overflow = "";
      document.documentElement.style.paddingRight = "";
      document.body.style.overflow = "";
      document.body.style.paddingRight = "";
    }
  }, [isOpen]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="overflow-hidden">
          {/* Sidebar + Overlay */}
          <Sidebar isOpen={isOpen} setIsOpen={setIsOpen} />

          {/* Fixed Navbar (scroll handling is internal now) */}
          <Navbar isOpen={isOpen} setIsOpen={setIsOpen} />

          {/* Main Content (moves right when sidebar opens) */}
          <div className={`transition-transform duration-300 ${isOpen ? "translate-x-64" : "translate-x-0"}`}>
            {children}
          </div>
          <DoctorFooter />
        </div>
      </body>
    </html>
  );
}
